### ISSUE TITLE
Redirects to Installation Page after Application server resart again

### ISSUE THREAD

**Issue by Atul1413** [valgen/mvcwcms#1]
Dear Sir,
I Deployed application of local server ,now i am having an issue it's redirects to Installation page after application server restart.
i used serverState mode in web.config to preserve User Data,but it's coudn't help me .

Warm Regards,
Atul S
+91 2041061330

**Comment by valgen** [comment]
Hi Atul,

You don't have to use sessionState, it's pointless for this.

You need to follow the installation procedure on the server where you have deployed.

You should see this message: "To complete this installation, you must know some information regarding your database server (connection string)."

Also pay attention on the 3 check-boxes: "Create database if it doesn't exist", "Ignore warning if database exists" and "Reset database if it exists".

If you need more help you can contact us on our website for payed support.

Regards

**Comment by Atul1413** [comment]
Dear Sir,
it's already done,i deployed the application on live server,if application server restarted then it's redirects to installation page. now i want to persist users data when app server restarted.

Warm Regards,
Atul S
+91 02041061330

**Comment by valgen** [comment]
Open the Web.config currently deployed on your server and check the connectionStrings node.

If it is empty like this `<connectionStrings />` or it's totally missing then you have not deployed your application correctly.

If it's not empty then I don't know how to help without looking into your code/configuration.

**Comment by Atul1413** [comment]
Dear Sir,
Suppose i download & deployed application on server as you had mentioned in 1st reply,it's working perfectly(showing all application content ). then i added the content whatever client demanded.
then i goes to **Windows Features-->Internet Information Services->and Restart the application server manualy(IIS Server)** now my application again Redirects to Installation Page which i have already done.
i am attaching webconfig as well with this email id for your reference.

**Comment by valgen** [comment]
You have just posted your connection strings here in GitHub. Are you aware that this is publicly available to anyone?
I've delete your file.

**Comment by Atul1413** [comment]
thanks for the removing file from github. sir any solution to persist the session.

Warm Regards,
Atul S
+91 02041061330

**Comment by valgen** [comment]
Send me the URL of your application via our contact form here: [http://mvcwcms.com/en/contact/](http://mvcwcms.com/en/contact/)

**Comment by Atul1413** [comment]
![unable to serialize the session state](https://user-images.githubusercontent.com/11453397/32220267-215aae04-be57-11e7-9ee0-2a3c6ba68c8f.PNG)
